#server:
#  port: 8087
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/bdcc-realm
#          jwk-set-uri: http://localhost:8080/realms/bdcc-realm/protocol/openid-connect/certs
#
#  application:
#    name: inv-service
#  datasource:
#    url: jdbc:h2:mem:products-db
#  h2:
#    console:
#      enabled: true
#  cloud:
#    config:
#      enabled: false
#    discovery:
#      enabled: false
